# Generated by Django 3.0.6 on 2020-06-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200601_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='has_barcode',
        ),
        migrations.AddField(
            model_name='categoriaprodotto',
            name='has_barcode',
            field=models.BooleanField(default=True),
        ),
    ]
