# Generated by Django 3.0.6 on 2020-06-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200601_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaprodotto',
            name='has_barcode',
            field=models.BooleanField(),
        ),
    ]
