# Generated by Django 3.0.6 on 2020-06-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200601_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaprodotto',
            name='unit',
            field=models.IntegerField(default=1),
        ),
    ]
