# Generated by Django 3.0.6 on 2020-06-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_categoriaprodotto_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='qnt',
            field=models.IntegerField(default=0),
        ),
    ]
