# Generated by Django 3.0.6 on 2020-06-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_prodotto_qnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='barcode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
